server:
  shutdown: graceful

spring:
  datasource:
    url: jdbc:h2:mem:mockdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  jooq:
    sql-dialect: h2


  h2:
    console:
      enabled: true